### ISSUE TITLE
Cant install uri 0.11.1

### ISSUE THREAD

**Issue by oscarshaitan** [dart-lang/pub-dartlang-dart#1159]
URL: https://pub.dartlang.org/packages/uri

My dependecies on my pubspec.yaml:

```
name: map_test
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  uri: "^0.11.1"
   The following adds the Cupertino Icons font to your application.
   Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
```

My console result for the flutter packages get:

```
E:\Android\map_test>flutter packages get
Running "flutter packages get" in map_test...
Package uri has no versions that match >=0.11.1 <0.12.0 derived from:
- map_test depends on version ^0.11.1
pub get failed (1)
```

happens with new proyects or started ones.
