### ISSUE TITLE
 package's pubspec.yaml

### ISSUE THREAD

**Issue by Erhie** [dart-lang/pub-dartlang-dart#1535]
URL: https://pub.dartlang.org/packages/launcher_assist#-installing-tab-

indenting it is important, so in my pubspec.yaml this functions:
```
dependencies:
  flutter:
    sdk: flutter
  launcher_assist: ^1.0.4
```
