### ISSUE TITLE
Strange health problems for some flutter packages.

### ISSUE THREAD

**Issue by ariedov** [dart-lang/pub-dartlang-dart#1728]
Hi, there are some packages that scored 0 for health, but they are working properly when included and used.

For instance: 
* flutter_redux: https://pub.dartlang.org/packages/flutter_redux#-analysis-tab-
* spritewidget: https://pub.dartlang.org/packages/spritewidget#-analysis-tab-

**Comment by quentinleguennec** [comment]
Got the same. I updated the package twice today. First time was fine second time I got the same issue as above.

slide_container: https://pub.dartlang.org/packages/flutter_redux#-analysis-tab-

**Comment by isoos** [comment]
@quentinleguennec: We had a new release where we've upgraded our Flutter version to `0.10.1`. It is possible that the first deploy was on the previous version, and the new one exposes more issues.

@ariedov: the analysis exposed 30+ errors in the package. It is possible that previous Flutter versions were OK using them. Do you know which version are you on?

**Comment by p69** [comment]
Got the same with https://pub.dartlang.org/packages/dartea#-analysis-tab-
I'm using Flutter 0.10.1, library is compiling without problems. Tried to use it via pub in fresh projects - everything works fine.

**Comment by isoos** [comment]
One common thing in these reports I've noticed is the reference to mixins. `pana` (the analysis library) enables `superMixins` in the custom [`analysis-options.yaml`](https://github.com/dart-lang/pana/blob/master/lib/src/analysis_options.dart#L35) we are using. I'm not following Flutter closely, maybe something did change in that area?

**Comment by p69** [comment]
@isoos I've tried to run analyzer locally with this options
```yaml
analyzer:
  language:    
    enableSuperMixins: true  
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODOs in the code
    todo: ignore
# Source of linter options:
# http://dart-lang.github.io/linter/lints/options/options.html
linter:
  rules:
    - camel_case_types
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - unrelated_type_equality_checks
    - valid_regexps
```
It shows me `No issues found!`.
