### ISSUE TITLE
test_runner overwrites pubspec.yaml (was: How do I run the tests?)

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dartlang-dart#18]
Should I just run the the individual files under test/ ? If there's a document that tells me how to test my patch, let me know and I'll give it a shot.

Thanks!

**Comment by mkustermann** [comment]
Something like this should do it:

```dart
pub-dartlang-dart/ $ cd app
pub-dartlang-dart/app $ pub get
pub-dartlang-dart/app $ pub global activate test_runner
pub-dartlang-dart/app $ pub global run test_runner
```

**Comment by sethladd** [comment]
Thanks, will try it out. Looks like I'm missing something?

```
~/Code/pub-dartlang-dart/app[case-insensitive-changelog*] $ pub global run test_runner

Checking Dart SDK binaries...
Dart SDK binaries OK.

Looking for Dart project in "./"...
Found project "foobar_pkg".

Looking for test suites...
Found 4 test suites (4 Standalone VM, 0 Dartium).  

Running all tests...
Test suite failed: configuration_test.dart
Detailed results of test suite configuration_test.dart:
┌──────────────────────────────────────────────────────
│ 
│ Unhandled exception:
│ Uncaught Error: Load Error: FileSystemException: Cannot open file, path = '/Users/sethladd/Code/pub-dartlang-dart/app/test/__test_runner/packages/unittest/vm_config.dart' (OS Error: No such file or directory, errno = 2)
│ Stack Trace:
│ #0      _asyncLoadErrorCallback (dart:_builtin:268)
│ #1      _asyncLoadError (dart:_builtin:287)
│ #2      _loadDataAsyncLoadPort.<anonymous closure> (dart:_builtin:304)
│ #3      _RootZone.runUnary (dart:async/zone.dart:1155)
│ #4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
│ #5      _Future._propagateToListeners (dart:async/future_impl.dart:577)
│ #6      _Future._complete (dart:async/future_impl.dart:358)
│ #7      _cancelAndValue (dart:async/stream_pipe.dart:62)
│ #8      Stream.first.<anonymous closure> (dart:async/stream.dart:911)
│ #9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
│ #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
│ #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
│ #12     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)
│ #13     _StreamController._add (dart:async/stream_controller.dart:570)
│ #14     _StreamController.add (dart:async/stream_controller.dart:516)
│ #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)
│ 
│ #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
│ #1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
│ #2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
│ #3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
│ #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
└──────────────────────────────────────────────────────
Test suite failed: handlers_test.dart
Detailed results of test suite handlers_test.dart:
┌─────────────────────────────────────────────────
│ 
│ Unhandled exception:
│ Uncaught Error: Load Error: FileSystemException: Cannot open file, path = '/Users/sethladd/Code/pub-dartlang-dart/app/test/__test_runner/packages/unittest/vm_config.dart' (OS Error: No such file or directory, errno = 2)
│ Stack Trace:
│ #0      _asyncLoadErrorCallback (dart:_builtin:268)
│ #1      _asyncLoadError (dart:_builtin:287)
│ #2      _loadDataAsyncLoadPort.<anonymous closure> (dart:_builtin:304)
│ #3      _RootZone.runUnary (dart:async/zone.dart:1155)
│ #4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
│ #5      _Future._propagateToListeners (dart:async/future_impl.dart:577)
│ #6      _Future._complete (dart:async/future_impl.dart:358)
│ #7      _cancelAndValue (dart:async/stream_pipe.dart:62)
│ #8      Stream.first.<anonymous closure> (dart:async/stream.dart:911)
│ #9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
│ #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
│ #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
│ #12     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)
│ #13     _StreamController._add (dart:async/stream_controller.dart:570)
│ #14     _StreamController.add (dart:async/stream_controller.dart:516)
│ #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)
│ 
│ #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
│ #1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
│ #2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
│ #3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
│ #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
└─────────────────────────────────────────────────
Test suite failed: tarball_storage_namer_test.dart
Detailed results of test suite tarball_storage_namer_test.dart:
┌──────────────────────────────────────────────────────────────
│ 
│ Unhandled exception:
│ Uncaught Error: Load Error: FileSystemException: Cannot open file, path = '/Users/sethladd/Code/pub-dartlang-dart/app/test/__test_runner/packages/unittest/vm_config.dart' (OS Error: No such file or directory, errno = 2)
│ Stack Trace:
│ #0      _asyncLoadErrorCallback (dart:_builtin:268)
│ #1      _asyncLoadError (dart:_builtin:287)
│ #2      _loadDataAsyncLoadPort.<anonymous closure> (dart:_builtin:304)
│ #3      _RootZone.runUnary (dart:async/zone.dart:1155)
│ #4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
│ #5      _Future._propagateToListeners (dart:async/future_impl.dart:577)
│ #6      _Future._complete (dart:async/future_impl.dart:358)
│ #7      _cancelAndValue (dart:async/stream_pipe.dart:62)
│ #8      Stream.first.<anonymous closure> (dart:async/stream.dart:911)
│ #9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
│ #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
│ #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
│ #12     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)
│ #13     _StreamController._add (dart:async/stream_controller.dart:570)
│ #14     _StreamController.add (dart:async/stream_controller.dart:516)
│ #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)
│ 
│ #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
│ #1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
│ #2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
│ #3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
│ #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
└──────────────────────────────────────────────────────────────
Test suite failed: backend_test.dart
Detailed results of test suite backend_test.dart:
┌────────────────────────────────────────────────
│ 
│ Unhandled exception:
│ Uncaught Error: Load Error: FileSystemException: Cannot open file, path = '/Users/sethladd/Code/pub-dartlang-dart/app/test/__test_runner/packages/unittest/vm_config.dart' (OS Error: No such file or directory, errno = 2)
│ Stack Trace:
│ #0      _asyncLoadErrorCallback (dart:_builtin:268)
│ #1      _asyncLoadError (dart:_builtin:287)
│ #2      _loadDataAsyncLoadPort.<anonymous closure> (dart:_builtin:304)
│ #3      _RootZone.runUnary (dart:async/zone.dart:1155)
│ #4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
│ #5      _Future._propagateToListeners (dart:async/future_impl.dart:577)
│ #6      _Future._complete (dart:async/future_impl.dart:358)
│ #7      _cancelAndValue (dart:async/stream_pipe.dart:62)
│ #8      Stream.first.<anonymous closure> (dart:async/stream.dart:911)
│ #9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
│ #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
│ #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
│ #12     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)
│ #13     _StreamController._add (dart:async/stream_controller.dart:570)
│ #14     _StreamController.add (dart:async/stream_controller.dart:516)
│ #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)
│ 
│ #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
│ #1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
│ #2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
│ #3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
│ #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
└────────────────────────────────────────────────

Summary: ALL 4 TEST SUITE(S) FAILED.
```

**Comment by sethladd** [comment]
Here's my pubspec.lock:

```
~/Code/pub-dartlang-dart/app[case-insensitive-changelog*] $ cat pubspec.lock
# Generated by pub
# See http://pub.dartlang.org/doc/glossary.html#lockfile
packages:
  collection:
    description: collection
    source: hosted
    version: "1.1.1"
  crypto:
    description: crypto
    source: hosted
    version: "0.9.0"
  gcloud:
    description: gcloud
    source: hosted
    version: "0.1.4+1"
  googleapis:
    description: googleapis
    source: hosted
    version: "0.5.5"
  googleapis_beta:
    description: googleapis_beta
    source: hosted
    version: "0.9.0"
  http:
    description: http
    source: hosted
    version: "0.11.2"
  http_parser:
    description: http_parser
    source: hosted
    version: "0.0.2+6"
  path:
    description: path
    source: hosted
    version: "1.3.5"
  source_span:
    description: source_span
    source: hosted
    version: "1.1.2"
  stack_trace:
    description: stack_trace
    source: hosted
    version: "1.3.2"
  string_scanner:
    description: string_scanner
    source: hosted
    version: "0.1.3+1"
```

Does that match what you have?
