### ISSUE TITLE
pub.dartlang.org shows a different latest version of a package in the search result than in the package version history. This also applies for the modification date.

### ISSUE THREAD

**Issue by christophhermann** [dart-lang/pub-dartlang-dart#44]
This issue has been described by me in https://github.com/dart-lang/sdk/issues/24729 but maybe this issue tracker is better suited, since the `pub` command relies on the (JSON) information from pub.dartlang.org

**Comment by zoechi** [comment]
This is normal behavior. Versions with a `-` after the patch number are pre-releases (like 1.0.0-rc.3). Also `pub get` or `pub upgrade` ignore pre-releases if your version constraint in `pubspec.yaml` doesn't contain a `-`.

**Comment by christophhermann** [comment]
Thank you very much for that quick answer!

Then I understand even less why pub can't resolve the dependencies. The dependency ist `polymer: ^1.0.0-rc.2`. This follows the described pattern. But `pub` says it can only find 0.16.3+3 and therefore the dependencies cannot be satisfied.

**Comment by zoechi** [comment]
If your Dart version is older than the version required by a dependency, this produces misleading error messages. This is a known issue and will hopefully be fixed eventually. Without checking, AFAIR you need at least 1.12 for Polymer.

**Comment by christophhermann** [comment]
The dart version is `Dart VM version: 1.12.2 (Wed Oct 21 06:56:12 2015) on "macos_x64"`. I also tried it with Dart 1.12.1. The same issue.

**Comment by zoechi** [comment]
Do you have any other dependencies in your pubspec.yaml   besides the ones required for Polymer? Maybe one of these additional dependencies conflicts with dependencies required by Polymer. Can you please post your pubspec.yaml?

**Comment by zoechi** [comment]
Sorry, just saw you already provided the info in the linked issue.

**Comment by christophhermann** [comment]
I do:

```bash
$ stagehand web-polymer
$ pub get
```

The generated pubspec.yaml is 

```yaml
name: 'test'
version: 0.0.1
description: A web app built using polymer.dart.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.1
  polymer: ^1.0.0-rc.2
  reflectable: ^0.3.1
  web_components: ^0.12.0

transformers:
- web_components:
    entry_points: web/index.html
- reflectable:
    entry_points: web/index.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
```
The `~/.pub-cache` directory is empty.

`pub get`outputs 

```
Resolving dependencies... (5.8s) 
Package polymer has no versions that match >=1.0.0-rc.2 <2.0.0 derived from:
- test depends on version ^1.0.0-rc.2
```
