### ISSUE TITLE
fludex doesn't show Flutter Icon and not available under Flutter packages

### ISSUE THREAD

**Issue by hemanthrajv** [dart-lang/pub-dartlang-dart#549]
https://pub.dartlang.org/search?q=fludex

**Comment by isoos** [comment]
@hemanthrajv: The platform classification of your package failed, because you import packages that are **not** in your `pubspec.yaml` as dependencies:
```
import 'package:logging/logging.dart';
import 'package:meta/meta.dart';
```

For these, you must specify them, for example:
```
dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.3
  meta: ^1.1.2 
```

If you update the pubspec with the dependencies and re-publish, it shall be able to classify the platform properly and it will show up.
