### ISSUE TITLE
flame does not show up as a "flutter" package

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/pub-dartlang-dart#562]
https://pub.dartlang.org/packages/flame

Note it has no Flutter logo shown.  @kevmoo  (I hope this was the right repo to file in.)

**Comment by isoos** [comment]
@eseidelGoogle: analysis shows an error: `Error(s) in lib/util.dart: The class 'ServicesBinding' can't be used as a mixin because it extends a class other than Object.` (line:40, col:46). Only packages without errors get platform classification.

**Comment by kevmoo** [comment]
@eseidelGoogle – the v2 work includes making these types of issues easy to debug. The bits @isoos are available for authors – just obscured at the moment

**Comment by eseidelGoogle** [comment]
FYI @luanpotter

**Comment by luanpotter** [comment]
@eseidelGoogle, thanks for noticing and letting me know :)

So, this is weird indeed, because I ran both `flutter analyze` and `flutter packages pub publish --dry-run` and neither gave me any errors nor warnings whatsoever. How could I be able to get a log of these obscured errors, as you put it?

As regards the error itself, I don't really understand it, it seems that Dart 1.13 "supports mixins that can extend from classes other than Object" [[1](https://www.dartlang.org/articles/language/mixins)]. Now admittedly my min SDK version was 1.8, so I bumped that up, and yet, no logo. It also required the `--supermixin` flag, and I don't know if that is used or not in this hidden analysis PUB is performing.

Note that what I'm trying to achieve is not without precedent, as it's done by flutter itself:

```dart
class WidgetsFlutterBinding extends BindingBase with SchedulerBinding, GestureBinding, ServicesBinding, RendererBinding, WidgetsBinding {
    // ...
}
```
On line 847 of `flutter/lib/src/widgets/binding.dart`.

Forgive me for my understanding of Dart's mixins (and the language itself) is rather limited yet.

**Comment by isoos** [comment]
The simplest way to debug what is happening or missing is to add the following `analysis_options.yaml` file to your project:

```
analyzer:
  strong-mode: true

# Source of linter options:
# http://dart-lang.github.io/linter/lints/options/options.html

linter:
  rules:
    - camel_case_types
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - unrelated_type_equality_checks
    - valid_regexps
```

and run `dartanalyzer .` in the project root. It'll list the errors and warnings that we are looking at, and if there is a pending error, please fix it.
