### ISSUE TITLE
code in headers gets resized

### ISSUE THREAD

**Issue by srawlins** [dart-lang/pub-dartlang-dart#68]
See https://pub.dartlang.org/packages/build

Each header has a bit of code in it, and the code is being resized, because of this CSS:

```css
code {
  font-size: 13px;
}
```
