### ISSUE TITLE
Markdown rendering issue with code in package homepage

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dartlang-dart#749]
URL: https://pub.dartlang.org/packages/trotter

Compare this display from pub:

![2](https://user-images.githubusercontent.com/5479/33694016-b49719e0-daaa-11e7-966c-2e0f3f2d862b.png)

With this output from bitbucket:

![1](https://user-images.githubusercontent.com/5479/33694021-b9a81092-daaa-11e7-92d8-87fa19af0ae4.png)

Here is the raw file: https://bitbucket.org/ram6ler/dart_trotter/raw/6bf3276f576499587ebf4e0d35a6b460a05113a9/README.md

**Comment by kevmoo** [comment]
Need to add a style for `pre > code` that matches `.hljs` from  `github.css`

```css
pre > code {
  display: block;
  overflow-x: auto;
  padding: 0.5em;
  color: #333;
  background: #f8f8f8;
}
```
