### ISSUE TITLE
pana should enable super mixins over flutter packages

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#829]
URL: https://pub.dartlang.org/packages/pdrpulm#-analysis-tab-

Pretty easy

```yaml
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
```
