### ISSUE TITLE
Dig into the "/edge-cdn" and "/edge-cdn-nocache" requests we get

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/pub-dartlang-dart#84]
The production server is frequently getting requests on `/edge-cdn` and `/edge-cdn-nocache`. They don't hit the server via the hostname, but rather via the external IP and come via http (**not https**).

```
  Method: GET
  Requested URI: http://<external-ip>/edge-cdn
  Headers:
    accept: [*/*]
    accept-encoding: [gzip, deflate]
    host: [IP]
    user-agent: [GoogleStackdriverMonitoring-UptimeChecks(https://cloud.google.com/monitoring)]
    via: [1.1 google]
    x-cloud-trace-context: [.../...]
    x-forwarded-for: [IP1, IP2]
    x-forwarded-proto: [http]
```

We should dig into this issue with stack driver monitoring.
